# Generated by Django 3.0.2 on 2020-01-07 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(max_length=254)),
                ('twitterAccount', models.CharField(max_length=45)),
                ('telegramAccount', models.CharField(max_length=45)),
                ('dataCadastro', models.DateField(auto_now_add=True)),
                ('dataModificacao', models.DateField(auto_now=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não se aplica')], max_length=1)),
            ],
        ),
    ]
